### ISSUE TITLE
New bug with calibration transfer

### ISSUE THREAD

**Issue by rlbyrne** [EoRImaging/FHD#265] opened 2021-06-10 22:54 UTC
I am attempting to transfer calibration and I'm encountering this error:
% Illegal subscript range: <No name>.
% Execution halted at: VIS_CALIBRATE      83
   /home/ubuntu/MWA/FHD/fhd_core/calibration/vis_calibrate.pro
%                      FHD_MAIN          135
   /home/ubuntu/MWA/FHD/fhd_core/fhd_main.pro

My keywords are:
      return_cal_visibilities = 0
      catalog_file_path = 0
      diffuse_calibrate = 0
      diffuse_model = 0
      model_visibilities = 1
      model_catalog_file_path = '/home/ubuntu/pol_leakage_corrected_catalogs_Jun2021/'+string(obs_id)+'_decon_catalog_pol_leakage_corrected.sav'
      cal_bp_transfer = 0
      transfer_calibration = '/home/ubuntu/calibration_transferred/'+string(obs_id)+'_cal.sav'
      transfer_weights = '/home/ubuntu/calibration_transferred/'+string(obs_id)+'_flags.sav'
      rephase_weights = 0
      restrict_hpx_inds = 0
      hpx_radius = 15
      subtract_sidelobe_catalog = filepath('GLEAM_v2_plus_rlb2019',root=rootdir('FHD'),subdir='catalog_data')
      return_sidelobe_catalog = 1
      dft_threshold = 0
      ring_radius = 0
      write_healpix_fits = 1
      max_baseline = 50
      debug_region_grow = 0
      n_pol = 4
      dimension = 208
      image_filter_fn = 'filter_uv_optimal'
      time_cut = -4
      nside = 512

**Comment by isullivan** [comment] 2021-06-10 23:12
Could you send me the two files you are restoring here: `'/home/ubuntu/calibration_transferred/'+string(obs_id)+'_cal.sav'` and ` '/home/ubuntu/calibration_transferred/'+string(obs_id)+'_flags.sav'`? I assume this is failing for all obsids. If so, could you send me those files for obsid 1061316296 (assuming that is part of your processing run).

**Comment by rlbyrne** [comment] 2021-06-10 23:13
1061316296 is not part of the processing run (this is all diffuse survey). I can get you an obs from the survey, though. How should I transfer it to you?

**Comment by isullivan** [comment] 2021-06-10 23:20
In that case you can just send me the `cal.sav` and `flags.sav` file this error was from, and I will figure it out.
If you have sufficient space in Google Drive or Dropbox for the uvfits file, that will be slow but I could get it that way. I can probably debug the crash without it, though.

**Comment by rlbyrne** [comment] 2021-06-10 23:26
I just sent you the cal and flags files via Slack

**Comment by isullivan** [comment] 2021-06-11 21:31
I believe this is fixed with the linked PR #266 . I tested it with other data, and was able to reproduce the bug. The problem was that you have 4 polarizations and were looping over all of them, but in calibration you only have x and y, not xx, yy, xy, and yx.

Separately, please check whether you intended to use `dimension = 208`. That looks like a typo, and in general powers of two are preferred.

**Comment by isullivan** [comment] 2021-06-18 21:32
If that was a carefully chosen number it should be okay, it just looked like it might be a typo from 2048. Powers of two are more computationally efficient for the many FFTs used in FHD, but if the array is that small it will hardly matter.

**Comment by rlbyrne** [comment] 2021-06-18 21:36
Thanks! I think we're good on aliasing because we aren't gridding any visibilities beyond 50 wavelengths (there is aliasing from _that_ cut, but that's another matter).

**Comment by isullivan** [comment] 2021-06-18 21:48
It might be okay, but I would strongly recommend at least doing a test with a larger dimension. I don't think you want to be using anything outside of the central dimension/2 width of pixels for any important calculations.

**Comment by rlbyrne** [comment] 2021-06-18 21:50
I think there are real reasons to steer away from a lot of zeros in the uv plane for the diffuse. Because of normalization issues, we can't use a filling factor to normalize the diffuse like we would with other weighting schemes. I worked through the math a while back and I decided our best approach was to limit the size of the uv plane.

**Closed** 2021-06-25 22:35 UTC
Labels: bug
